name: Post Release Process
on:
    release:
        types: [published]
concurrency: ${{ github.workflow }}
jobs:
    release:
        uses: matrix-org/matrix-js-sdk/.github/workflows/release-action.yml@develop
        secrets:
            ELEMENT_BOT_TOKEN: ${{ secrets.ELEMENT_BOT_TOKEN }}

    npm:
        name: Publish to npm
        needs: release
        uses: matrix-org/matrix-js-sdk/.github/workflows/release-npm.yml@develop
        secrets:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    docs:
        name: Publish Documentation
        needs: release
        runs-on: ubuntu-latest
        steps:
            - name: 🧮 Checkout code
              uses: actions/checkout@v4

            - name: 🧮 Checkout gh-pages
              uses: actions/checkout@v4
              with:
                  ref: gh-pages
                  path: _docs

            - name: 🔧 Yarn cache
              uses: actions/setup-node@v4
              with:
                  cache: "yarn"

            - name: 🔨 Install dependencies
              run: "yarn install --frozen-lockfile"

            - name: 🔨 Install symlinks
              run: |
                  sudo apt-get update
                  sudo apt-get install -y symlinks

            - name: 📖 Generate docs
              run: |
                  yarn tpv purge --yes --out _docs --stale --major 10
                  yarn gendoc
                  symlinks -rc _docs

            - name: 🔨 Set up git
              run: |
                  git config --global user.email "releases@riot.im"
                  git config --global user.name "RiotRobot"

            - name: 🚀 Deploy
              run: |
                  git add . --all
                  git commit -m "Update docs"
                  git push
              working-directory: _docs
